### ISSUE TITLE
Derive recipe metadata from pivotal_workstation repo

### ISSUE THREAD

**Issue by patcon** [tommyh/solo_wizard#2]
As per pivotal/pivotal_workstation#94

For testing, we can just fork pivotal_workstation and copy solo_wizards descriptions into recipe descriptions in `metadata.rb`, adding category hashes like `#GeneralSoftware`. Thinking we might want to make them more concise later, but will just copy for now.

New to rails, so this will be a little slow for me, but it's a good opportunity to sort things out :)

**Comment by tommyh** [comment]
I added by comments on the pivotal_workstation ticket.  if they decide the data should be stored in a fork of pivotal_workstation project (or just in the solo wizard project), then we can switch to this thread for the discussion.

**Comment by tommyh** [comment]
Hi,

The corresponding issue on pivotal_workstation repo has been closed due to inactivity.  Do you think you'll have any time to work on this in the next few weeks?  If not, I will probably close this and we can reopen if needed.

Tom

**Comment by patcon** [comment]
Pivotal_workstation isn't getting any love from me lately, so probably best to close for now :)
