### ISSUE TITLE
A couple of bad recipes

### ISSUE THREAD

**Issue by acgetchell** [tommyh/solo_wizard#7]
Chef::Exceptions::RecipeNotFound

---

could not find recipe ag for cookbook pivotal_workstation

Chef::Exceptions::RecipeNotFound

---

could not find recipe bash_path_order for cookbook pivotal_workstation

Chef::Exceptions::RecipeNotFound

---

could not find recipe bash_path_order for cookbook pivotal_workstation

Chef::Exceptions::RecipeNotFound

---

could not find recipe bash_profile-aliases for cookbook pivotal_workstation

Chef::Exceptions::RecipeNotFound

---

could not find recipe bash_profile-better_history for cookbook pivotal_workstation

Chef::Exceptions::RecipeNotFound

---

could not find recipe gem_no_rdoc_no_ri for cookbook pivotal_workstation

**Comment by tommyh** [comment]
Thanks for the heads up!  Right now I have to manually update solo_wizard each time pivotal_workstation updates their list of recipes (add or remove).  This helped me focus on the core of the project and launch fast, but is a maintenance pain.

I will try to update the recipes list this weekend.

**Comment by bearlake** [comment]
Also:

Chef::Exceptions::RecipeNotFound

could not find recipe bash_profile-ctrl-o for cookbook pivotal_workstation

Chef::Exceptions::RecipeNotFound

could not find recipe bash_profile-git_completion for cookbook pivotal_workstation

**Comment by conraddecker** [comment]
Just thought I'd offer a little help but it looks like all of the bash_profile recipes are gone as well.

Regardless...thanks for your work on this, it's been super helpful!

**Comment by tommyh** [comment]
Just to touch base, I will be working on this tomorrow.  The plan is have a cron job which will hits the pivotal_workstation cookbook and updates the solowizard recipes.  They have been updating the cookbook far too often for me to keep up manually.

Thanks for pointing these out and bringing it to my attention.  I'll comment here when it's been fixed.

**Comment by tommyh** [comment]
Update - The "fetch from github" job has been run, so solowizard should be fully up to date.

I haven't created the cronjob yet, because the cleanup task can tax the database, so I need to pay for a non-free database tier.  Hopefully will get around to that this week.

**Comment by tommyh** [comment]
The cron task to keep recipes up to date is now running on solowizard.com.  Thanks for opening/adding to this issue.  Closing it.

Note: The cron job will update the recipes from the pivotal_workstation github repo every 10 minutes.  So it's possible that they'll delete a recipe and you'll create a script with that recipe within that window.  If this happens to you, you can:
- come back a few minutes later and recreate your solowizard script
- manually update your solowizard script and delete the offending line
